--- 
title: "Introduction to Geographic Information Systems"
author: ""
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

## Workshop Objectives

This workshop introduces participants to spatial data analysis and visualization using R Studio. It will do so through a substantive exploration of systemic racism in traffic police stops. In particular, we will take a large (over 3,000,000 observations) dataset of Colorado traffic stops released by the [Stanford Open Policing Project](https://openpolicing.stanford.edu/), and develop a simple county-level measure of the magnitude of anti-Black racial bias in traffic police stops during the year 2010. We will then display county-level variation in our bias index on a map of Colorado counties.

The workshop has several learning objectives. Among other things, you will learn how to:

* Read in datasets (both tabular and spatial) into R Studio
* Clean and process data in R Studio using *tidyverse* functions (i.e. subset data, reshape data, summarize datasets, join different datasets together, and define new variables)
* Make static maps and interactive web maps in R Studio using the *tmap* package
* Export your maps from R Studio so they can be embedded in your reports and websites

Most broadly, and most importantly, you will gain an appreciation for how to use real-world social scientific data to better understand important social problems, and use this understanding to reflect on possible ways to address these problems. 

## Data

The workshop makes use of the following three datasets:

* Colorado State Patrol traffic stops data, available through the Stanford Open Policing Project (mentioned above). The data is available at the project website [here](https://openpolicing.stanford.edu/data/), under the "CO" heading; if you're downloading the data straight from the website, be sure to use the "State Patrol" data.
* A dataset of county-level demographic data (based on the 2010 decennial census), which your instructors generated prior to the workshop. See the Appendix to this tutorial to see how this census data was extracted.
* A spatial dataset of Colorado counties, available through the [Colorado GeoLibrary](https://geo.colorado.edu/), a curated online archive of Colorado-related spatial data. The specific dataset we will use is available [here](https://geo.colorado.edu/catalog/47540-5e712aeda3d91e0009f59fc7). Note that this spatial dataset is stored as a shapefile, which is a common file format used to store spatial data. 

For convenience, all of this data can be downloaded from this [folder](https://www.dropbox.com/sh/sd7wwi5b0r9s9mn/AABscRHrEvXRoX26e_yqEiTFa?dl=0). 

## R and R Studio Installation



```{}
library(tidyverse)
library(tmap)
library(sf)
```








