<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Defining an index of racial bias in traffic stops | Introduction to Geographic Information Systems</title>
  <meta name="description" content="5 Defining an index of racial bias in traffic stops | Introduction to Geographic Information Systems" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Defining an index of racial bias in traffic stops | Introduction to Geographic Information Systems" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Defining an index of racial bias in traffic stops | Introduction to Geographic Information Systems" />
  
  
  



<meta name="date" content="2022-02-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="transforming-data.html"/>
<link rel="next" href="mapping-the-bias-index.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.4.1/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to GIS</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#workshop-objectives"><i class="fa fa-check"></i><b>1.1</b> Workshop Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data"><i class="fa fa-check"></i><b>1.2</b> Data</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#r-and-r-studio-installation"><i class="fa fa-check"></i><b>1.3</b> R and R Studio Installation</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#the-r-studio-interface"><i class="fa fa-check"></i><b>1.4</b> The R Studio Interface</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>1.5</b> Installing and loading packages</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#setting-your-working-directory"><i class="fa fa-check"></i><b>1.6</b> Setting your working directory</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="loading-data.html"><a href="loading-data.html"><i class="fa fa-check"></i><b>2</b> Loading data</a></li>
<li class="chapter" data-level="3" data-path="cleaning-and-filtering-data.html"><a href="cleaning-and-filtering-data.html"><i class="fa fa-check"></i><b>3</b> Cleaning and filtering data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="cleaning-and-filtering-data.html"><a href="cleaning-and-filtering-data.html#create-a-year-field"><i class="fa fa-check"></i><b>3.1</b> Create a “Year” field</a></li>
<li class="chapter" data-level="3.2" data-path="cleaning-and-filtering-data.html"><a href="cleaning-and-filtering-data.html#filter-by-year"><i class="fa fa-check"></i><b>3.2</b> Filter by year</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="transforming-data.html"><a href="transforming-data.html"><i class="fa fa-check"></i><b>4</b> Transforming Data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="transforming-data.html"><a href="transforming-data.html#tabulate-county-level-count-of-traffic-stops-by-race"><i class="fa fa-check"></i><b>4.1</b> Tabulate county-level count of traffic stops by race</a></li>
<li class="chapter" data-level="4.2" data-path="transforming-data.html"><a href="transforming-data.html#reshape-the-data"><i class="fa fa-check"></i><b>4.2</b> Reshape the data</a></li>
<li class="chapter" data-level="4.3" data-path="transforming-data.html"><a href="transforming-data.html#calculate-total-stops-for-each-county-in-co_county_summary_wide"><i class="fa fa-check"></i><b>4.3</b> Calculate total stops for each county in <code>co_county_summary_wide</code></a></li>
<li class="chapter" data-level="4.4" data-path="transforming-data.html"><a href="transforming-data.html#clean-co_county_summary_wide-and-assign-to-new-object"><i class="fa fa-check"></i><b>4.4</b> Clean <code>co_county_summary_wide</code> and assign to new object</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="defining-an-index-of-racial-bias-in-traffic-stops.html"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html"><i class="fa fa-check"></i><b>5</b> Defining an index of racial bias in traffic stops</a>
<ul>
<li class="chapter" data-level="5.1" data-path="defining-an-index-of-racial-bias-in-traffic-stops.html"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#read-in-and-join-2010-census-data-to-co_county_black_stops"><i class="fa fa-check"></i><b>5.1</b> Read in and join 2010 census data to <code>co_county_black_stops</code></a></li>
<li class="chapter" data-level="5.2" data-path="defining-an-index-of-racial-bias-in-traffic-stops.html"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#join-census-data-to-co_county_black_stops"><i class="fa fa-check"></i><b>5.2</b> Join census data to <code>co_county_black_stops</code></a></li>
<li class="chapter" data-level="5.3" data-path="defining-an-index-of-racial-bias-in-traffic-stops.html"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#define-the-variables-that-will-be-used-in-the-bias-index"><i class="fa fa-check"></i><b>5.3</b> Define the variables that will be used in the bias index</a></li>
<li class="chapter" data-level="5.4" data-path="defining-an-index-of-racial-bias-in-traffic-stops.html"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#calculate-the-bias-index"><i class="fa fa-check"></i><b>5.4</b> Calculate the bias index</a></li>
<li class="chapter" data-level="5.5" data-path="defining-an-index-of-racial-bias-in-traffic-stops.html"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#compute-summary-statistics-for-the-bias-index"><i class="fa fa-check"></i><b>5.5</b> Compute summary statistics for the bias index</a></li>
<li class="chapter" data-level="5.6" data-path="defining-an-index-of-racial-bias-in-traffic-stops.html"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#visualize-county-level-variation-in-the-bias-index-using-ggplot"><i class="fa fa-check"></i><b>5.6</b> Visualize county-level variation in the bias index using <code>ggplot</code></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="mapping-the-bias-index.html"><a href="mapping-the-bias-index.html"><i class="fa fa-check"></i><b>6</b> Mapping the bias index</a>
<ul>
<li class="chapter" data-level="6.1" data-path="mapping-the-bias-index.html"><a href="mapping-the-bias-index.html#read-in-and-view-the-shapefile-of-co-counties"><i class="fa fa-check"></i><b>6.1</b> Read in and view the shapefile of CO counties</a></li>
<li class="chapter" data-level="6.2" data-path="mapping-the-bias-index.html"><a href="mapping-the-bias-index.html#join-co_counties_census_trafficstops-to-the-shapefile-of-colorado-counties"><i class="fa fa-check"></i><b>6.2</b> Join <code>co_counties_census_trafficstops</code> to the shapefile of Colorado counties</a></li>
<li class="chapter" data-level="6.3" data-path="mapping-the-bias-index.html"><a href="mapping-the-bias-index.html#display-the-bias-index-on-a-map-of-colorado-counties"><i class="fa fa-check"></i><b>6.3</b> Display the bias index on a map of Colorado counties</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="mapping-the-bias-index.html"><a href="mapping-the-bias-index.html#make-a-rough-draft-of-a-map"><i class="fa fa-check"></i><b>6.3.1</b> Make a rough draft of a map</a></li>
<li class="chapter" data-level="6.3.2" data-path="mapping-the-bias-index.html"><a href="mapping-the-bias-index.html#make-a-map-with-custom-breaks"><i class="fa fa-check"></i><b>6.3.2</b> Make a map with custom breaks</a></li>
<li class="chapter" data-level="6.3.3" data-path="mapping-the-bias-index.html"><a href="mapping-the-bias-index.html#make-a-map-with-custom-colors"><i class="fa fa-check"></i><b>6.3.3</b> Make a map with custom colors</a></li>
<li class="chapter" data-level="6.3.4" data-path="mapping-the-bias-index.html"><a href="mapping-the-bias-index.html#make-a-categorical-map"><i class="fa fa-check"></i><b>6.3.4</b> Make a categorical map</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="refining-and-formatting-the-maps-of-the-colorado-traffic-stop-bias-index.html"><a href="refining-and-formatting-the-maps-of-the-colorado-traffic-stop-bias-index.html"><i class="fa fa-check"></i><b>7</b> Refining and formatting the maps of the Colorado traffic-stop bias index</a>
<ul>
<li class="chapter" data-level="7.1" data-path="refining-and-formatting-the-maps-of-the-colorado-traffic-stop-bias-index.html"><a href="refining-and-formatting-the-maps-of-the-colorado-traffic-stop-bias-index.html#refining-the-map-of-the-continuous-bias_index-variable"><i class="fa fa-check"></i><b>7.1</b> Refining the map of the continuous “bias_index” variable</a></li>
<li class="chapter" data-level="7.2" data-path="refining-and-formatting-the-maps-of-the-colorado-traffic-stop-bias-index.html"><a href="refining-and-formatting-the-maps-of-the-colorado-traffic-stop-bias-index.html#refining-the-categorical-map"><i class="fa fa-check"></i><b>7.2</b> Refining the categorical map</a></li>
<li class="chapter" data-level="7.3" data-path="refining-and-formatting-the-maps-of-the-colorado-traffic-stop-bias-index.html"><a href="refining-and-formatting-the-maps-of-the-colorado-traffic-stop-bias-index.html#making-a-dynamic-map-of-the-bias-index"><i class="fa fa-check"></i><b>7.3</b> Making a dynamic map of the bias index</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="exporting-maps.html"><a href="exporting-maps.html"><i class="fa fa-check"></i><b>8</b> Exporting maps</a></li>
<li class="chapter" data-level="9" data-path="summary-scripts.html"><a href="summary-scripts.html"><i class="fa fa-check"></i><b>9</b> Summary scripts</a>
<ul>
<li class="chapter" data-level="9.1" data-path="summary-scripts.html"><a href="summary-scripts.html#summary-script-to-prepare-clean-and-process-data-for-mapping"><i class="fa fa-check"></i><b>9.1</b> Summary script to prepare, clean, and process data for mapping</a></li>
<li class="chapter" data-level="9.2" data-path="summary-scripts.html"><a href="summary-scripts.html#summary-script-for-map-of-continuous-bias_index-variable"><i class="fa fa-check"></i><b>9.2</b> Summary script for map of continuous “bias_index” variable</a></li>
<li class="chapter" data-level="9.3" data-path="summary-scripts.html"><a href="summary-scripts.html#summary-script-for-categorical-map"><i class="fa fa-check"></i><b>9.3</b> Summary script for categorical map</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="reflections-and-discussion-questions.html"><a href="reflections-and-discussion-questions.html"><i class="fa fa-check"></i><b>10</b> Reflections and Discussion Questions</a></li>
<li class="chapter" data-level="11" data-path="conclusion-and-further-reading.html"><a href="conclusion-and-further-reading.html"><i class="fa fa-check"></i><b>11</b> Conclusion and Further Reading</a></li>
<li class="chapter" data-level="12" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>12</b> References</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="using-tidycensus-to-extract-relevant-census-data.html"><a href="using-tidycensus-to-extract-relevant-census-data.html"><i class="fa fa-check"></i><b>A</b> Using tidycensus to extract relevant census data</a>
<ul>
<li class="chapter" data-level="A.1" data-path="using-tidycensus-to-extract-relevant-census-data.html"><a href="using-tidycensus-to-extract-relevant-census-data.html#step-1-define-your-variables"><i class="fa fa-check"></i><b>A.1</b> Step 1: Define your variables</a></li>
<li class="chapter" data-level="A.2" data-path="using-tidycensus-to-extract-relevant-census-data.html"><a href="using-tidycensus-to-extract-relevant-census-data.html#step-2-extract-the-variables-using-tidycensus"><i class="fa fa-check"></i><b>A.2</b> Step 2: Extract the variables using tidycensus</a></li>
<li class="chapter" data-level="A.3" data-path="using-tidycensus-to-extract-relevant-census-data.html"><a href="using-tidycensus-to-extract-relevant-census-data.html#step-3-clean-the-tidycensus-dataset"><i class="fa fa-check"></i><b>A.3</b> Step 3: Clean the tidycensus dataset</a></li>
<li class="chapter" data-level="A.4" data-path="using-tidycensus-to-extract-relevant-census-data.html"><a href="using-tidycensus-to-extract-relevant-census-data.html#step-4-define-new-variables"><i class="fa fa-check"></i><b>A.4</b> Step 4: Define new variables</a></li>
<li class="chapter" data-level="A.5" data-path="using-tidycensus-to-extract-relevant-census-data.html"><a href="using-tidycensus-to-extract-relevant-census-data.html#step-5-finalize-and-export-the-dataset"><i class="fa fa-check"></i><b>A.5</b> Step 5: Finalize and export the dataset</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Geographic Information Systems</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="defining-an-index-of-racial-bias-in-traffic-stops" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Defining an index of racial bias in traffic stops</h1>
<p>Let’s briefly take stock of where we are. We started with a massive dataset (over 3,000,000 observations) of traffic patrol stops in the state of Colorado over the course of a decade. Over several steps, we have worked our way to a county-level dataset containing information on the total number of stops, and the number of those stops involving a Black motorist, over the course of the year 2010. That dataset looks something like this:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb31-1" aria-hidden="true" tabindex="-1"></a>co_county_black_stops</span></code></pre></div>
<pre><code>## # A tibble: 64 × 3
## # Rowwise:  county_name
##    county_name       black_stops total_stops
##    &lt;chr&gt;                   &lt;int&gt;       &lt;int&gt;
##  1 Adams County             1208       34350
##  2 Alamosa County             43        4478
##  3 Arapahoe County          1819       17520
##  4 Archuleta County           28        5091
##  5 Baca County                61        1511
##  6 Bent County                46        1808
##  7 Boulder County            192       13053
##  8 Broomfield County          22        1095
##  9 Chaffee County             37        6521
## 10 Cheyenne County            38        1106
## # … with 54 more rows</code></pre>
<p>Now, let’s think about how to use this information to develop a measure of the extent to which traffic police stops may have been driven by racial bias (whether conscious or unconscious) against Black motorists. We might expect that in a discrimination-free world, the share of traffic stops for a given racial group will reflect their share of the overall 17-and older population (we’ll consider the 17 and over population as our baseline, since that is the demographic eligible to drive). For example, if the Black percentage of a given county’s 17-and-over population is 5%, we could form a simple baseline expectation that in a discrimination-free world where “driving while Black” is not effectively criminalized, the percentage of traffic stops involving Black motorists would not exceed 5%. To the extent that the percentage of traffic stops involving Black motorists <strong>did</strong> exceed 5%, we might assume a statistical pattern consistent with racial discrimination.</p>
<p>Based on this logic, a simple county-level indicator of anti-Black bias in traffic stops would simply be the difference between the percentage of traffic stops in a given county involving Black motorists, and the percentage of the county’s overall population that is Black:</p>
<p><strong>County-Level Traffic Stop Bias Index</strong>=
<em>(Percentage of County Traffic Stops Involving Black Motorists)</em>-<em>(Percentage of County’s 17-and-over Population that is Black)</em></p>
<p>As the value of this difference rises and we see higher values for the bias index, we might infer higher levels of possible discrimination in traffic stops.</p>
<p>Of course, this is a very simple index, and sets aside many complexities (for example, commuting patterns, among other things). However, despite its simplicity, the intuition behind the index is often used in the published social science literature on the topic; at least to a first approximation, therefore, this index will give us a meaningful way to identify counties in which the behavior of traffic patrol might merit greater public scrutiny, on account of disproportionately high stop-rates for the Black population.</p>
<p>Let’s create this index for Colorado counties in the year 2010. Note that we already have the data to compute the first part of the bias index (i.e. the percentage of traffic stops involving Black motorists); this is contained in <code>co_county_black_stops</code>:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb33-1" aria-hidden="true" tabindex="-1"></a>co_county_black_stops</span></code></pre></div>
<pre><code>## # A tibble: 64 × 3
## # Rowwise:  county_name
##    county_name       black_stops total_stops
##    &lt;chr&gt;                   &lt;int&gt;       &lt;int&gt;
##  1 Adams County             1208       34350
##  2 Alamosa County             43        4478
##  3 Arapahoe County          1819       17520
##  4 Archuleta County           28        5091
##  5 Baca County                61        1511
##  6 Bent County                46        1808
##  7 Boulder County            192       13053
##  8 Broomfield County          22        1095
##  9 Chaffee County             37        6521
## 10 Cheyenne County            38        1106
## # … with 54 more rows</code></pre>
<p>Let’s therefore turn to calculating the second part of the index: the percentage of each county’s population that is Black. We’ll carry out this calculation using demographic data from the 2010 decennial census.</p>
<div id="read-in-and-join-2010-census-data-to-co_county_black_stops" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Read in and join 2010 census data to <code>co_county_black_stops</code></h2>
<p>First, let’s read in the census dataset that was provided to you at the start of workshop using the <code>read_csv</code> function, and assign it to an object named <code>co_counties_census_2010</code>:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in census data and assigns to object named &quot;co_counties_census_2010&quot;</span></span>
<span id="cb35-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb35-2" aria-hidden="true" tabindex="-1"></a>co_counties_census_2010<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">&quot;co_county_decennial_census.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ───────────────────────────────────────────────────────────────────────
## cols(
##   GEOID = col_character(),
##   County = col_character(),
##   total_pop = col_double(),
##   total_black_pop_over17 = col_double(),
##   total_pop_over17 = col_double()
## )</code></pre>
<p>Let’s print the contents of this census dataset:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prints contents of &quot;co_counties_census_2010&quot;</span></span>
<span id="cb37-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb37-2" aria-hidden="true" tabindex="-1"></a>co_counties_census_2010</span></code></pre></div>
<pre><code>## # A tibble: 64 × 5
##    GEOID County          total_pop total_black_pop_over17 total_pop_over17
##    &lt;chr&gt; &lt;chr&gt;               &lt;dbl&gt;                  &lt;dbl&gt;            &lt;dbl&gt;
##  1 08023 Costilla County      3524                     18             2788
##  2 08025 Crowley County       5823                    556             5034
##  3 08027 Custer County        4255                     37             3525
##  4 08029 Delta County        30952                    139            24101
##  5 08031 Denver County      600158                  45338           471392
##  6 08035 Douglas County     285465                   2447           198453
##  7 08033 Dolores County       2064                      4             1602
##  8 08049 Grand County        14843                     43            11825
##  9 08039 Elbert County       23086                    122            17232
## 10 08041 El Paso County     622263                  27280           459587
## # … with 54 more rows</code></pre>
<p>Note that it contains county-level information on the overall population (i.e. all age groups and all racial categories), the 17+ population (for all racial groups), and the Black 17+ population. We can use the latter two variables to compute the second part of our bias index.</p>
</div>
<div id="join-census-data-to-co_county_black_stops" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Join census data to <code>co_county_black_stops</code></h2>
<p>Before doing so, however, let’s join the census dataset we just viewed (<code>co_counties_census_2010</code>) to the dataset containing information on county-level police stops (<code>co_county_black_stops</code>); this will allow us to calculate the bias index using the information from the single dataset that results from this join.</p>
<p>The code below uses the <code>full_join</code> function to join <code>co_counties_census_2010</code> (the second argument), to <code>co_county_black_stops</code> (the first argument), using the “county_name” column (from <code>co_county_black_stops</code>) and the “County” column (from <code>co_counties_census_2010</code>) as the join fields; it assigns the dataset which results from the join to a new object named <code>co_counties_census_trafficstops</code>:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Joins &quot;co_counties_census_2010&quot; to &quot;co_counties_black_stops&quot; using the &quot;county_name&quot; and &quot;County&quot; fields as the join fields; assigns the product of the join to an object named &quot;co_counties_census_trafficstops&quot;</span></span>
<span id="cb39-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb39-3" aria-hidden="true" tabindex="-1"></a>co_counties_census_trafficstops<span class="ot">&lt;-</span><span class="fu">full_join</span>(co_county_black_stops, co_counties_census_2010,</span>
<span id="cb39-4"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb39-4" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">by=</span><span class="fu">c</span>(<span class="st">&quot;county_name&quot;</span><span class="ot">=</span><span class="st">&quot;County&quot;</span>))</span></code></pre></div>
<p>When we open <code>co_counties_census_trafficstops</code>, we should see information from both of the constituent datasets (<code>co_county_black_stops</code> and <code>co_counties_census_2010</code>):</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prints contents of &quot;co_counties_census_trafficstops&quot;</span></span>
<span id="cb40-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb40-2" aria-hidden="true" tabindex="-1"></a>co_counties_census_trafficstops</span></code></pre></div>
<pre><code>## # A tibble: 64 × 7
## # Rowwise:  county_name
##    county_name       black_stops total_stops GEOID total_pop total_black_pop_… total_pop_over17
##    &lt;chr&gt;                   &lt;int&gt;       &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt;             &lt;dbl&gt;            &lt;dbl&gt;
##  1 Adams County             1208       34350 08001    441603              9396           315480
##  2 Alamosa County             43        4478 08003     15445               142            11617
##  3 Arapahoe County          1819       17520 08005    572003             40558           424679
##  4 Archuleta County           28        5091 08007     12084                19             9676
##  5 Baca County                61        1511 08009      3788                15             2974
##  6 Bent County                46        1808 08011      6499               486             5403
##  7 Boulder County            192       13053 08013    294567              1961           231813
##  8 Broomfield County          22        1095 08014     55889               415            41237
##  9 Chaffee County             37        6521 08015     17809               264            14821
## 10 Cheyenne County            38        1106 08017      1836                 4             1386
## # … with 54 more rows</code></pre>
</div>
<div id="define-the-variables-that-will-be-used-in-the-bias-index" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Define the variables that will be used in the bias index</h2>
<p>Now that we have all the information in one dataset, let’s calculate the constituent parts of the bias index. The code below takes the current <code>co_counties_census_trafficstops</code> that we created above, and then uses the <code>mutate</code> function to create two new variables. The first variable, named “black_stop_pct”, is defined as the percentage of traffic stops that involved a Black motorist. The second variable, named “black_pop_pct”, is defined as the percentage of a given county’s 17+ population that is Black. The dataset that includes these two new variables is assigned back to <code>co_counties_census_trafficstops</code>:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Takes &quot;co_counties_census_trafficstops&quot; and then creates two new variables; one new variable is named &quot;black_stop_pct&quot; (the Black percentage of traffic stops) and the other is &quot;black_pop_pct&quot; (the Black percentage of the over-17 population; assigns the updated dataset back to &quot;co_counties_census_trafficstops&quot;</span></span>
<span id="cb42-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb42-3" aria-hidden="true" tabindex="-1"></a>co_counties_census_trafficstops<span class="ot">&lt;-</span></span>
<span id="cb42-4"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb42-4" aria-hidden="true" tabindex="-1"></a>  co_counties_census_trafficstops <span class="sc">%&gt;%</span> </span>
<span id="cb42-5"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb42-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">black_stop_pct=</span>((black_stops<span class="sc">/</span>total_stops)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb42-6"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb42-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">black_pop_pct=</span>((total_black_pop_over17<span class="sc">/</span>total_pop_over17)<span class="sc">*</span><span class="dv">100</span>))</span></code></pre></div>
<p>Having created these two new variables (i.e. the components of the bias index we’ll calculate below) in <code>co_counties_census_trafficstops</code>, let’s view the contents below:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prints contents of &quot;co_counties_census_trafficstops&quot; object</span></span>
<span id="cb43-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb43-2" aria-hidden="true" tabindex="-1"></a>co_counties_census_trafficstops</span></code></pre></div>
<pre><code>## # A tibble: 64 × 9
## # Rowwise:  county_name
##    county_name       black_stop_pct black_pop_pct black_stops total_stops GEOID total_pop
##    &lt;chr&gt;                      &lt;dbl&gt;         &lt;dbl&gt;       &lt;int&gt;       &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt;
##  1 Adams County               3.52          2.98         1208       34350 08001    441603
##  2 Alamosa County             0.960         1.22           43        4478 08003     15445
##  3 Arapahoe County           10.4           9.55         1819       17520 08005    572003
##  4 Archuleta County           0.550         0.196          28        5091 08007     12084
##  5 Baca County                4.04          0.504          61        1511 08009      3788
##  6 Bent County                2.54          9.00           46        1808 08011      6499
##  7 Boulder County             1.47          0.846         192       13053 08013    294567
##  8 Broomfield County          2.01          1.01           22        1095 08014     55889
##  9 Chaffee County             0.567         1.78           37        6521 08015     17809
## 10 Cheyenne County            3.44          0.289          38        1106 08017      1836
## # … with 54 more rows, and 2 more variables: total_black_pop_over17 &lt;dbl&gt;,
## #   total_pop_over17 &lt;dbl&gt;</code></pre>
</div>
<div id="calculate-the-bias-index" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Calculate the bias index</h2>
<p>Now that we have the two components of the traffic stop bias index in <code>co_counties_census_trafficstops</code> (“black_stop_pct”, and “black_pop_pct”), all that is left for us to do is create a new variable, which we’ll call “bias_index”, that is calculated by taking the difference between “black_stop_pct” and “black_pop_pct.” The code below creates this new “bias_index” variable in <code>co_counties_census_trafficstops</code>, and assigns the dataset with this new variable back to <code>co_counties_census_trafficstops</code>:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creates new variable in &quot;co_counties_census_trafficstops&quot; named &quot;bias_index&quot; that is defined as the difference between the existing &quot;black_stop_pct&quot; and &quot;black_pop_pct&quot; variables</span></span>
<span id="cb45-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb45-2" aria-hidden="true" tabindex="-1"></a>co_counties_census_trafficstops<span class="ot">&lt;-</span>co_counties_census_trafficstops <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb45-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">mutate</span>(<span class="at">bias_index=</span>black_stop_pct<span class="sc">-</span>black_pop_pct)</span></code></pre></div>
<p>Note that the “bias_index” variable is now in the dataset assigned to the <code>co_counties_census_trafficstops</code> object:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prints contents of &quot;co_counties_census_trafficstops&quot;</span></span>
<span id="cb46-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb46-2" aria-hidden="true" tabindex="-1"></a>co_counties_census_trafficstops</span></code></pre></div>
<pre><code>## # A tibble: 64 × 10
## # Rowwise:  county_name
##    county_name  bias_index black_stop_pct black_pop_pct black_stops total_stops GEOID total_pop
##    &lt;chr&gt;             &lt;dbl&gt;          &lt;dbl&gt;         &lt;dbl&gt;       &lt;int&gt;       &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt;
##  1 Adams County      0.538          3.52          2.98         1208       34350 08001    441603
##  2 Alamosa Cou…     -0.262          0.960         1.22           43        4478 08003     15445
##  3 Arapahoe Co…      0.832         10.4           9.55         1819       17520 08005    572003
##  4 Archuleta C…      0.354          0.550         0.196          28        5091 08007     12084
##  5 Baca County       3.53           4.04          0.504          61        1511 08009      3788
##  6 Bent County      -6.45           2.54          9.00           46        1808 08011      6499
##  7 Boulder Cou…      0.625          1.47          0.846         192       13053 08013    294567
##  8 Broomfield …      1.00           2.01          1.01           22        1095 08014     55889
##  9 Chaffee Cou…     -1.21           0.567         1.78           37        6521 08015     17809
## 10 Cheyenne Co…      3.15           3.44          0.289          38        1106 08017      1836
## # … with 54 more rows, and 2 more variables: total_black_pop_over17 &lt;dbl&gt;,
## #   total_pop_over17 &lt;dbl&gt;</code></pre>
<p>We can use this information to calculate an aggregated bias index for the state of Colorado as a whole in the year 2010:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculates the total number of Black traffic stops in Colorado and assigns the value to an object named &quot;colorado_total_black_stops&quot;</span></span>
<span id="cb48-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-2" aria-hidden="true" tabindex="-1"></a>colorado_total_black_stops<span class="ot">&lt;-</span><span class="fu">sum</span>(co_counties_census_trafficstops<span class="sc">$</span>black_stops, <span class="at">na.rm=</span>T)</span>
<span id="cb48-3"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Caclulates the total number of traffic stops in Colorado and assigns the value to an object named &quot;colorado_total_stops&quot;</span></span>
<span id="cb48-5"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-5" aria-hidden="true" tabindex="-1"></a>colorado_total_stops<span class="ot">&lt;-</span><span class="fu">sum</span>(co_counties_census_trafficstops<span class="sc">$</span>total_stops, <span class="at">na.rm=</span>T)</span>
<span id="cb48-6"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculates the total 17+ Black population in CO and assigns the value to an object named &quot;colorado_17plus_blackpopulation&quot;</span></span>
<span id="cb48-8"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-8" aria-hidden="true" tabindex="-1"></a>colorado_17plus_blackpopulation<span class="ot">&lt;-</span><span class="fu">sum</span>(co_counties_census_trafficstops<span class="sc">$</span>total_black_pop_over17, <span class="at">na.rm=</span>T)</span>
<span id="cb48-9"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculates the total 17+ population in CO and assigns the value to an object named &quot;colorado_17_plus_overall&quot;</span></span>
<span id="cb48-11"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-11" aria-hidden="true" tabindex="-1"></a>colorado_17_plus_overall<span class="ot">&lt;-</span><span class="fu">sum</span>(<span class="fu">sum</span>(co_counties_census_trafficstops<span class="sc">$</span>total_pop_over17), <span class="at">na.rm=</span>T)</span>
<span id="cb48-12"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-13"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculates the percentage of CO traffic patrol stops and assigns the value to an object named &quot;black_stop_pct_CO&quot;</span></span>
<span id="cb48-14"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-14" aria-hidden="true" tabindex="-1"></a>black_stop_pct_CO<span class="ot">&lt;-</span>(colorado_total_black_stops<span class="sc">/</span>colorado_total_stops)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb48-15"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-16"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculates the percentage of the Colorado 17+ population that is Black and assigns the value to an object named &quot;black_over17_population_pct_CO&quot;</span></span>
<span id="cb48-17"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-17" aria-hidden="true" tabindex="-1"></a>black_over17_population_pct_CO<span class="ot">&lt;-</span>(colorado_17plus_blackpopulation<span class="sc">/</span>colorado_17_plus_overall)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb48-18"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-19"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculates the bias index for the state of Colorado as a whole, by computing the difference beween &quot;black_stop_pct_CO&quot; and &quot;black_over17_population_pct_CO&quot;; assigns the result to an object named &quot;CO_bias_index&quot;</span></span>
<span id="cb48-20"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb48-20" aria-hidden="true" tabindex="-1"></a>CO_bias_index<span class="ot">&lt;-</span>(black_stop_pct_CO)<span class="sc">-</span>(black_over17_population_pct_CO)</span></code></pre></div>
<p>Now, let’s print the value of <code>CO_bias_index</code>:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb49-1" aria-hidden="true" tabindex="-1"></a>CO_bias_index</span></code></pre></div>
<pre><code>## [1] -1.112616</code></pre>
<p>Interestingly, the value of the aggregate state-level bias index is negative; specifically, this result suggests that the Black share of traffic stops in Colorado is about 1.11 percentage points less than the Black share of Colorado’s 17+ population. At first glance, this might suggest that “driving while black” is not criminalized in Colorado ( during the year under consideration), according to our simple bias indicator. However, it might still be the case that there are specific areas in the state where racial bias in traffic stops <strong>is</strong> a problem, and focusing on an aggregated state-level measure of the bias index obscures possible micro-level variation in patterns of bias with respect to traffic stops. Documenting this micro-level variation is be an important task, since it would allow us to identify “problem areas” that might be excessively punitive towards Black drivers, and thereby target efforts at reform. The remainder of the lesson attempts to document this micro-geography of systemic bias in traffic stops.</p>
</div>
<div id="compute-summary-statistics-for-the-bias-index" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Compute summary statistics for the bias index</h2>
<p>Recall that we have a measure of the bias index for each county in Colorado; a simple way to document the spatial distribution in the bias index would be to simply compute some basic summary statistics for the “bias_index” variable in <code>co_counties_census_trafficstops</code>, which will give us a sense of how the bias index varies across counties. We can generate these summary statistics using the <code>describe</code> function.
Below, the argument to the <code>describe</code> function, which reads <code>co_counties_census_trafficstops$bias_index</code> simply specifies that we want summary statistics for the “bias_index” variable that is in the dataset assigned to the <code>co_counties_census_trafficstops</code> data object:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Produces summary statistics for &quot;bias_index&quot; variable calculated above</span></span>
<span id="cb51-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(co_counties_census_trafficstops<span class="sc">$</span>bias_index)</span></code></pre></div>
<pre><code>##    vars  n mean   sd median trimmed  mad   min  max range  skew kurtosis   se
## X1    1 62 0.53 2.04   0.47    0.65 0.59 -9.84 4.26  14.1 -2.45    10.67 0.26</code></pre>
<p>This table of summary statistics shows that the mean bias index across counties was 0.53 and the median value of the bias index was 0.47; this clearly suggests that even though the bias index for the state as a whole was negative, there are many counties with a <strong><em>positive</em></strong> bias index. In other words, many Colorado counties appear to have been stopping black motorists at disproportionately high rates. Moreover, there is a fairly large range in the bias index with respect to counties; the county with the largest value for “bias_index” had an index of 4.26 (i.e. the share of Black motorists stopped by the police was 4.26 percentage points higher than the share of Black county residents in the 17+ age demographic), while the county with the smallest value for the index had an index value of -9.84 (i.e. the share of Black motorists stopped by police was 9.84 percentage points lower than the share of Black county residents in the 17+ age demographic). These basic results suggest that a few outlier parts of the state where racial bias (as we are measuring it here) does not appear to be a problem are driving down the state’s overall bias index, despite the fact that in many areas of the state, Black motorists are subject to disproportionately aggressive policing. One way to quickly explore this possibility might be to create a quick visualization that conveys county-level variation in the bias index. In Section 5.6, we’ll visualize this county-level variation in the bias index on a simple graph.</p>
</div>
<div id="visualize-county-level-variation-in-the-bias-index-using-ggplot" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Visualize county-level variation in the bias index using <code>ggplot</code></h2>
<p>There are many possible ways to visualize county-level variation in the “bias_index” variable. Here, we’ll make a simply bar graph using <code>ggplot</code>, a popular visualization package that is part of the <em>tidyverse</em> suite of packages.</p>
<p>Before making this graph, let’s quickly make a new column in <code>co_counties_census_trafficstops</code>, named “County”, that takes the information in the existing “county_name” field (which takes the form of “<County Name> County”) and removes the part of the string that reads “County”. This will result in a cleaner-looking graph, since we can convey that our geographic units are counties in the graph’s title.</p>
<p>The following code takes the dataset currently assigned to the<code>co_counties_census_trafficstops</code> object, and then uses the mutate function to create a new field named “County”, that is populated by taking the existing “county_name” column and using the <code>str_remove</code> function to remove the part of the “county_name” strings that read “County”. It then assigns the modified dataset back to the <code>co_counties_census_trafficstops</code> object, which overwrites the previous version of the dataset:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb53-1" aria-hidden="true" tabindex="-1"></a>co_counties_census_trafficstops<span class="ot">&lt;-</span>co_counties_census_trafficstops <span class="sc">%&gt;%</span> </span>
<span id="cb53-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb53-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">mutate</span>(<span class="at">County=</span><span class="fu">str_remove</span>(county_name, <span class="st">&quot; County&quot;</span>))</span></code></pre></div>
<p>Let’s confirm that the new “County” field has been successfully created:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb54-1" aria-hidden="true" tabindex="-1"></a>co_counties_census_trafficstops</span></code></pre></div>
<pre><code>## # A tibble: 64 × 11
## # Rowwise:  county_name
##    county_name     County bias_index black_stop_pct black_pop_pct black_stops total_stops GEOID
##    &lt;chr&gt;           &lt;chr&gt;       &lt;dbl&gt;          &lt;dbl&gt;         &lt;dbl&gt;       &lt;int&gt;       &lt;int&gt; &lt;chr&gt;
##  1 Adams County    Adams       0.538          3.52          2.98         1208       34350 08001
##  2 Alamosa County  Alamo…     -0.262          0.960         1.22           43        4478 08003
##  3 Arapahoe County Arapa…      0.832         10.4           9.55         1819       17520 08005
##  4 Archuleta Coun… Archu…      0.354          0.550         0.196          28        5091 08007
##  5 Baca County     Baca        3.53           4.04          0.504          61        1511 08009
##  6 Bent County     Bent       -6.45           2.54          9.00           46        1808 08011
##  7 Boulder County  Bould…      0.625          1.47          0.846         192       13053 08013
##  8 Broomfield Cou… Broom…      1.00           2.01          1.01           22        1095 08014
##  9 Chaffee County  Chaff…     -1.21           0.567         1.78           37        6521 08015
## 10 Cheyenne County Cheye…      3.15           3.44          0.289          38        1106 08017
## # … with 54 more rows, and 3 more variables: total_pop &lt;dbl&gt;, total_black_pop_over17 &lt;dbl&gt;,
## #   total_pop_over17 &lt;dbl&gt;</code></pre>
<p>Now, we’re ready to use <code>ggplot</code> to make our bar graph.</p>
<p>The following code takes <code>co_counties_trafficstops</code>, and then uses the <code>drop_na</code> function to remove counties for which the “bias_index” value has an “NA” value (there are two such counties), so that they do not show up on the graph. It then enters the <code>ggplot</code> environment by calling the <code>ggplot</code> function. It then uses the <code>geom_col</code> function to indicate that the desired output is a bar graph. Within the <code>geom_col</code> function, the expression that reads <code>aes(x=County, y-bias_index)</code> specifies which variables we want to represent on the graph, and how we want to represent those variables (i.e. which variable do we want on the x- axis, and which variable on the y-axis?). The instructions used to translate the variables in a tabular dataset into a visual representation are known as an “aesthetic mapping”, which is abbreviated within the grammar of <code>ggplot</code> to <code>aes</code>. After specifiying that we want a bar graph based on the <code>co_counties_census_trafficstops</code> object (with the “County” column mapped to the x-axis and the “bias_index” column mapped to the y-axis), we use the <code>labs</code> function (short for “labels”) to designate the graph’s main title, and the labels for x and y axis. The next few lines of code customize the appearance of the axes. In <code>ggplot</code>, the <code>theme</code> function is a versatile function that helps to customize the appearance of a <code>ggplot</code> object; here, we set the <code>axis.title.x</code> argument equal to <code>element_text(size=9)</code>, which effectively sets the size of the x axis labels. In addition, we set the <code>plot.title</code> argument within the <code>theme</code> function equal to <code>element_text(hjust=0.5)</code>, which effectively center-justifies the plot’s main title. Next, we use the <code>scale_y_continuous</code> function to set the interval breaks of the y-axis; this range defined as a vector passed to the <code>breaks</code> argument, where each numeric element of the vector denotes a desired interval break. The <code>expand_limits</code> function allows us to expand the range of either axis beyond the range established by the axis interval markers; here, by specifying <code>y-c(-10,10)</code> as an argument to the <code>expand_limits</code> function, we effectively stretch out the y-axis range from -10 to 10, even though the highest legend break is set at 7.5. Finally, we assign the plot that is created with this code to a new object named <code>bias_graph</code>:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb56-1" aria-hidden="true" tabindex="-1"></a>bias_graph<span class="ot">&lt;-</span></span>
<span id="cb56-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb56-2" aria-hidden="true" tabindex="-1"></a>  co_counties_census_trafficstops <span class="sc">%&gt;%</span> </span>
<span id="cb56-3"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(bias_index) <span class="sc">%&gt;%</span> </span>
<span id="cb56-4"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb56-5"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb56-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x=</span>County, <span class="at">y=</span>bias_index))<span class="sc">+</span></span>
<span id="cb56-6"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb56-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;Racial Discrimination in Police Stops, by County (Colorado)&quot;</span>, <span class="at">x=</span><span class="st">&quot;County&quot;</span>, <span class="at">y=</span><span class="st">&quot;Bias Index=</span><span class="sc">\n</span><span class="st">Black Percentage of Overall Traffic Stops – Black Percentage of Overall Over-17 Population&quot;</span>)<span class="sc">+</span></span>
<span id="cb56-7"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb56-7" aria-hidden="true" tabindex="-1"></a>       <span class="fu">theme</span>(<span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>), <span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))<span class="sc">+</span>      </span>
<span id="cb56-8"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb56-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="sc">-</span><span class="fl">7.5</span>, <span class="sc">-</span><span class="dv">5</span>, <span class="sc">-</span><span class="fl">2.5</span>, <span class="dv">0</span>, <span class="fl">2.5</span>, <span class="dv">5</span>, <span class="fl">7.5</span>))<span class="sc">+</span></span>
<span id="cb56-9"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb56-9" aria-hidden="true" tabindex="-1"></a>       <span class="fu">expand_limits</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>))</span></code></pre></div>
<p>Let’s print the contents of <code>bias_graph</code> and see what the plot looks like; it will appear in the “plots” tab on the bottom-right of your R Studio interface.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb57-1" aria-hidden="true" tabindex="-1"></a>bias_graph</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>As we can see, the graph does show that certain counties have values around zero, or well below zero on the bias index, which drives down the overall value for the state; but in many other counties, the value of the “bias_index” variable is positive and substantively large. While the graph does convey valuable information, it’s a little bit confusing to look at; for example, the county names are squished together in a way that makes them unreadable.</p>
<p>A quick way to make the plot more readable is to invert the axes (such that counties are on the y-axis, and the bias index is arrayed along the x-axis). The code below is largely the same as the code in the previous code block. The differences are twofold, and contribute to a change in the map’s appearance. First, the argument to
<code>geom_col</code> looks a bit different. Instead of simply specifying <code>(aes(x=County, y=bias_index)</code>, we instead specify <code>(aes(x=reorder(County, bias_index), y=bias_index)</code>. The <code>reorder</code> function is essentially specifying that we want the x-axis variable (“County”), to be arrayed in descending order with respect to “bias_index”. Arraying the values in descending order makes for a graph that is easier to read. Second, we call the <code>coord_flip()</code> function, which inverts the axes such that the x-axis and y-axis (specified as arguments to <code>geom_col</code>) are inverted. We’ll assign this new plot to a new object named <code>bias_graph_inverted</code>:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-1" aria-hidden="true" tabindex="-1"></a>bias_graph_inverted<span class="ot">&lt;-</span></span>
<span id="cb58-2"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-2" aria-hidden="true" tabindex="-1"></a>  co_counties_census_trafficstops <span class="sc">%&gt;%</span> </span>
<span id="cb58-3"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">drop_na</span>(bias_index) <span class="sc">%&gt;%</span> </span>
<span id="cb58-4"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb58-5"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">reorder</span>(County, bias_index), <span class="at">y=</span>bias_index))<span class="sc">+</span></span>
<span id="cb58-6"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb58-7"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;Racial Discrimination in Police Stops, by County (Colorado)&quot;</span>, <span class="at">x=</span><span class="st">&quot;County&quot;</span>, <span class="at">y=</span><span class="st">&quot;Bias Index=</span><span class="sc">\n</span><span class="st">Black Percentage of Overall Traffic Stops – Black Percentage of Overall Over-17 Population&quot;</span>)<span class="sc">+</span></span>
<span id="cb58-8"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-8" aria-hidden="true" tabindex="-1"></a>        <span class="fu">theme</span>(<span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>), <span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))<span class="sc">+</span>      </span>
<span id="cb58-9"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="sc">-</span><span class="fl">7.5</span>, <span class="sc">-</span><span class="dv">5</span>, <span class="sc">-</span><span class="fl">2.5</span>, <span class="dv">0</span>, <span class="fl">2.5</span>, <span class="dv">5</span>, <span class="fl">7.5</span>))<span class="sc">+</span></span>
<span id="cb58-10"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb58-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">expand_limits</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>))</span></code></pre></div>
<p>Let’s view the revised plot:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="defining-an-index-of-racial-bias-in-traffic-stops.html#cb59-1" aria-hidden="true" tabindex="-1"></a>bias_graph_inverted</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-45-1.png" width="768" /></p>
<p>We can see that those relatively small changes produced a more readable and informative plot. We can get a clear sense of how the traffic stops bias index varies across Colorado counties, and identify the counties where policing practices appear the most punitive. The plot clearly conveys why focusing solely on aggregated statistics might be problematic: such measures have the potential to obscure more granular patterns of bias, such as those conveyed here, that should concern both policymakers and citizens.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="transforming-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mapping-the-bias-index.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/aranganath24/intro_GIS/edit/master/02-lesson.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/aranganath24/intro_GIS/blob/master/02-lesson.Rmd",
"text": null
},
"download": ["bookdownproj.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
